<?php declare(strict_types = 1);

return [
    [
        'CLI',
        '',
        [
            'OptimyTest\Controllers\NewsController',
            'index'
        ]
    ],
    [
        'CLI',
        'news',
        [
            'OptimyTest\Controllers\NewsController',
            'news'
        ]
    ],
    [
        'CLI',
        'news-add',
        [
            'OptimyTest\Controllers\NewsController',
            'add'
        ]
    ],
    [
        'CLI',
        'news-delete',
        [
            'OptimyTest\Controllers\NewsController',
            'delete'
        ]
    ],
    [
        'CLI',
        'comments',
        [
            'OptimyTest\Controllers\CommentController',
            'index'
        ]
    ],
    [
        'CLI',
        'comment',
        [
            'OptimyTest\Controllers\CommentController',
            'comment'
        ]
    ],
    [
        'CLI',
        'comment-add',
        [
            'OptimyTest\Controllers\CommentController',
            'add'
        ]
    ],
    [
        'CLI',
        'comment-delete',
        [
            'OptimyTest\Controllers\CommentController',
            'delete'
        ]
    ],
    [
        'CLI',
        'db-init',
        [
            'OptimyTest\Controllers\DatabaseController',
            'init'
        ]
    ],
];